version: "3"
networks:
  external_network:
  internal_network:
    internal: true

services:
  traefik:
    image: traefik
    restart: always
    command:
      - "--log.level=DEBUG"
      - "--api.dashboard=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.letsencrypt.acme.email=jayanath@gmail.com"
      - "--certificatesresolvers.letsencrypt.acme.storage=acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /data/traefik/acme.json:/acme.json
    labels:
      - traefik.enable=true
      # Dashboard
      - traefik.http.routers.traefik.rule=Host(`dashboard.jayforweb.com`)
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.routers.traefik.tls.certresolver=letsencrypt
      - traefik.http.routers.traefik.entrypoints=websecure
      - traefik.http.routers.traefik.middlewares=dashboardauth
      - traefik.http.middlewares.dashboardauth.basicauth.users=admin:$$apr1$$EcrvPa/i$$r4.HLJnYw/FNaGLCoIyPI1
      # HTTPS Redirect
      - traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)
      - traefik.http.routers.http-catchall.entrypoints=web
      - traefik.http.routers.http-catchall.middlewares=redirect-to-https@docker
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https

    networks:
      - external_network

  ghost:
    image: ghost:alpine
    restart: always
    environment:
      - url=http://jayforweb.com
    volumes:
      - /data/blogdir:/var/lib/ghost/content
    labels:
      - traefik.enable=true
      - traefik.http.routers.ghost.rule=Host(`jayforweb.com`)
      - traefik.http.routers.ghost.entrypoints=websecure
      - traefik.http.routers.ghost.tls.certresolver=letsencrypt
      - traefik.http.services.ghost.loadbalancer.server.port=2368
    networks:
      - external_network

  commento:
    image: registry.gitlab.com/commento/commento
    restart: always
    environment:
      COMMENTO_ORIGIN: http://commento.jayforweb.com
      COMMENTO_POSTGRES: postgres://postgres:postgres@db:5432/commento?sslmode=disable
      # COMMENTO_FORBID_NEW_OWNERS: false
    depends_on:
      - db
    labels:
      - traefik.enable=true
      - traefik.http.routers.commento.rule=Host(`commento.jayforweb.com`)
      - traefik.http.routers.commento.entrypoints=websecure
      - traefik.http.routers.commento.tls.certresolver=letsencrypt
      #- traefik.http.services.commento.loadbalancer.server.port=5535
    networks:
      - external_network
      - internal_network

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: commento
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - internal_network
    volumes:
      - /data/commento/data:/var/lib/postgresql/data
    labels:
      - traefik.enable=false