logLevel = "ERROR"

defaultEntryPoints = ["http", "https"]

[entryPoints]
[entryPoints.http]
address = ":80"

[entryPoints.http.redirect]
entryPoint = "https"
permanent = true

[entryPoints.https]
address = ":443"

[entryPoints.https.redirect]
regex = "^https://www.(.*)"
replacement = "https://$1"
permanent = true

[entryPoints.https.tls]
compress = true

[acme]
email = "jayanath@gmail.com"
storage = "acme.json"
entryPoint = "https"

[acme.tlsChallenge]
onHostRule = true

[acme.httpChallenge]
entryPoint = "http"

[[acme.domains]]
main = "jayforweb.com"
sans = ["www.jayforweb.com"]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "jayforweb.com"
watch = true
network = "web"
